name: Deploy

on:
  workflow_run:
    workflows: [ "Publish Docker image" ]
    types:
      - completed
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        env:
          CONTAINER_NAME: front
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: 22
          envs: CONTAINER_NAME
          script: |
            echo container name is "$CONTAINER_NAME"
            docker stop "$CONTAINER_NAME" || true
            docker rm "$CONTAINER_NAME" || true
            docker run --pull=always --name "$CONTAINER_NAME" -p 3000:80 -d nmzgnv/business-tinder-front:main
